// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWEMfvmEfGdsaVvEj-tAo9livZBWK2aQ',
    appId: '1:50476525367:web:d1c575b3e23f377a23dcb2',
    messagingSenderId: '50476525367',
    projectId: 'gazegenius-8fa95',
    authDomain: 'gazegenius-8fa95.firebaseapp.com',
    storageBucket: 'gazegenius-8fa95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hsWShPzypMQ9Slk9gE75kTRxSxXJ9RQ',
    appId: '1:50476525367:android:66714a9e420205b523dcb2',
    messagingSenderId: '50476525367',
    projectId: 'gazegenius-8fa95',
    storageBucket: 'gazegenius-8fa95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX4bWMnWBb3ywol6BYgOJpKW1yNVQ17x8',
    appId: '1:50476525367:ios:af8411180cb4e5ff23dcb2',
    messagingSenderId: '50476525367',
    projectId: 'gazegenius-8fa95',
    storageBucket: 'gazegenius-8fa95.appspot.com',
    iosClientId: '50476525367-t0t5adpet64p2o4p0lr910c17p1clsp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX4bWMnWBb3ywol6BYgOJpKW1yNVQ17x8',
    appId: '1:50476525367:ios:66b58d751e19f5ba23dcb2',
    messagingSenderId: '50476525367',
    projectId: 'gazegenius-8fa95',
    storageBucket: 'gazegenius-8fa95.appspot.com',
    iosClientId: '50476525367-mff322hjbikd1dbdh66gc51on3m43pop.apps.googleusercontent.com',
    iosBundleId: 'com.example.spm.RunnerTests',
  );
}
